
fmod NET-D-CONFIGURATION is 
--- a Net of local configurations
inc CONCERTO-D-CONFIGURATION .
sorts Net .
pr SET{LocalConfiguration} .
subsort Set{LocalConfiguration} < Net .
endfm


***(

    fmod NET-D-CONFIGURATION is 
--- a Net of local configurations
inc CONCERTO-D-CONFIGURATION .
sorts Net .
subsort LocalConfiguration < Net .
op emptyNet : -> Net [ctor] .
op _;_ : Net Net -> Net [ctor assoc comm id: emptyNet] .

endfm
)